###ADD
POST http://localhost:15080/graphql
Content-Type: application/json

{
  "query": "mutation AddDataPoints($dataPoints: [DataPointInput!]!) { addDataPoints(dataPoints: $dataPoints) { id userId timestamp sensorGlucose { mgdl sensorId calibration { slope intercept } } manualGlucose { mgdl } carbs { grams description } } }",
  "variables": {
    "dataPoints": [
      {
        "userId": "test_user",
        "timestamp": "2025-01-01T00:00:00Z",
        "sensorGlucose": {
          "mgdl": 100.0,
          "sensorId": "test_sensor"
        }
      },
      {
        "userId": "test_user",
        "timestamp": "2025-01-01T00:01:00Z",
        "sensorGlucose": {
          "mgdl": 100.1,
          "sensorId": "test_sensor"
        }
      }
    ]
  }
}

###GET
POST http://localhost:15080/graphql
Content-Type: application/json

{
  "query": "query GetDataPoints($userId: String!) { getDataPoints(userId: $userId) { id timestamp sensorGlucose { mgdl sensorId } manualGlucose { mgdl } carbs { grams description } } }",
  "variables": {
    "userId": "test_user"
  }
}
