name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Run tests
        run: ./gradlew test

      - name: Create release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +%Y-%m-%d)
          COUNT=$(git branch -r | grep "release-$DATE" | wc -l | xargs)
          NEW_COUNT=$((COUNT + 1))
          BRANCH_NAME="release-$DATE-$NEW_COUNT"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME

      - name: Build Docker image
        run: |
          docker build -t diasync-server:latest -f deploy/Dockerfile .

      - name: Deploy to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          DOMAIN: ${{ secrets.DOMAIN }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          chmod +x deploy/deploy.sh
          ./deploy/deploy.sh

      - name: Verify deployment
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          TIMEOUT=300  # 5 minutes in seconds
          INTERVAL=10  # Check every 10 seconds
          ELAPSED=0
          
          while [ $ELAPSED -lt $TIMEOUT ]; do
            if curl -s "https://${DOMAIN}/ping" | grep -q "pong"; then
              echo "Deployment successful: /ping endpoint responded with 'pong'"
              exit 0
            fi
            echo "Waiting for /ping endpoint... ($ELAPSED/$TIMEOUT seconds)"
            sleep $INTERVAL
            ELAPSED=$((ELAPSED + INTERVAL))
          done
          
          echo "Deployment failed: /ping endpoint did not respond with 'pong' within 5 minutes"
          git push origin --delete $BRANCH_NAME
          exit 1
